name: Release module

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: actions/checkout@v4

      - uses: rlespinasse/github-slug-action@v4

      - uses: release-drafter/release-drafter@v5
        id: create-release
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yaml
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update package.json
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          TAG_NAME=${{ steps.create-release.outputs.tag_name }}
          VERSION=$(echo "$TAG_NAME" | sed -E 's/^v//g')
          
          npm version $VERSION

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        id: publish-release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          publish: true
          prerelease: false
          filter-by-commitish: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
